# Numpy 

1 - Basically a python library used for fast numerical computation

In [ ]:
# step 1: importing numpy 
import numpy as np

In [ ]:
# step 2 : creating a Arrays
# 1D-dimension Array


arr1 = np.array( [1 , 2, 3 ,4, 5]    )
print(arr1)

[1 2 3 4 5]


#### 1D (A single column)
[1,2,3,4,5]

- shape 
    - (n,) --1 single column without rows


### 2D (A table or matrix with rows and columns)
- shape
    - (m, n)--- number of rows (m)
            ---- number of columns (n)
    - [1,2,3]
    - [4,5,6]

### 3D ( a stack of 2D array, a multiple tables)

- shape 
 (p, m, n) 
 - p = number of matrices
 - m = columns per matrix
 - n - rows per matrix

[1,2,3]   
[4,5,6]         

[7,8,9]     
[10,11,12]

In [ ]:
# 2D - dimension Array
arr2 = np.array( [
    [1,2,3],
    [4,5,6]
])


print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D - dimension array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
   
])

print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
# step 3 - Zeros & Ones

# Generate set of 0s
Zeros = np.zeros(  (2,3)  )

# Generate set of 1's
Ones = np.ones((2,3))

# Gnerate random number within a range and shape
rand = np.random.randint(0,100 ,(3,3))
print(rand)

[[36 98 18]
 [48 20 74]
 [98 36 48]]


In [19]:
# Step 4 Operations within ARRAY

 #- addition 
 #- multiplications
 #- mean (Average)

a = np.array([1,2,3])
b = np.array([4,5,6])



sum_ab = a + b
product_ab = a * b
mean_a = np.mean(a)


print("SUM", sum_ab)
print("Products", product_ab)
print("Average", mean_a)


SUM [5 7 9]
Products [ 4 10 18]
Average 2.0
